### ISSUE TITLE
assign domain error in proteins tutorials 

### ISSUE THREAD

**Issue by lidanwu** [MICS-Lab/novae#10]
Thanks for providing such great tools! I was able to follow the "main_usage" tutorial without issue. However, I encountered an error when following the ["proteins" tutorial](https://github.com/MICS-Lab/novae/blob/main/docs/tutorials/proteins.ipynb).

 Following the instructions, I was able to setup the model and trained it with 4 epochs using GPU. 
`model.fit(max_epochs=4, accelerator = "gpu",num_workers = 5)`
This part ran smoothly without error and I can use it to do `model.compute_representations()` without problem. 

However, it gave the following error when I did `model.assign_domains()`. How should I resolve this? 
I did not find any cell with all zeros for all features in `X`.
```
>>> model.assign_domains()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\project\venvDB\envNames\py310_novae\lib\site-packages\novae\model.py", line 468, in assign_domains
    adata.obs[key_added] = self.swav_head.map_leaves_domains(adata.obs[Keys.LEAVES], level)
  File "C:\Users\project\venvDB\envNames\py310_novae\lib\site-packages\novae\module\swav.py", line 250, in map_leaves_domains
    return series.map(lambda x: f"D{self.clusters_levels[-level, int(x[1:])]}" if isinstance(x, str) else x)
  File "C:\Users\project\venvDB\envNames\py310_novae\lib\site-packages\pandas\core\series.py", line 4700, in map
    new_values = self._map_values(arg, na_action=na_action)
  File "C:\Users\project\venvDB\envNames\py310_novae\lib\site-packages\pandas\core\base.py", line 921, in _map_values
    return algorithms.map_array(arr, mapper, na_action=na_action, convert=convert)
  File "C:\Users\project\venvDB\envNames\py310_novae\lib\site-packages\pandas\core\algorithms.py", line 1743, in map_array
    return lib.map_infer(values, mapper, convert=convert)
  File "lib.pyx", line 2972, in pandas._libs.lib.map_infer
  File "C:\Users\project\venvDB\envNames\py310_novae\lib\site-packages\novae\module\swav.py", line 250, in <lambda>
    return series.map(lambda x: f"D{self.clusters_levels[-level, int(x[1:])]}" if isinstance(x, str) else x)
  File "C:\Users\project\venvDB\envNames\py310_novae\lib\site-packages\novae\module\swav.py", line 202, in clusters_levels
    self.hierarchical_clustering()
  File "C:\Users\project\venvDB\envNames\py310_novae\lib\site-packages\novae\module\swav.py", line 228, in hierarchical_clustering
    _clustering.fit(X)
  File "C:\Users\project\venvDB\envNames\py310_novae\lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\Users\project\venvDB\envNames\py310_novae\lib\site-packages\sklearn\cluster\_agglomerative.py", line 989, in fit
    return self._fit(X)
  File "C:\Users\project\venvDB\envNames\py310_novae\lib\site-packages\sklearn\cluster\_agglomerative.py", line 1061, in _fit
    out = memory.cache(tree_builder)(
  File "C:\Users\project\venvDB\envNames\py310_novae\lib\site-packages\joblib\memory.py", line 312, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\project\venvDB\envNames\py310_novae\lib\site-packages\sklearn\cluster\_agglomerative.py", line 714, in _average_linkage
    return linkage_tree(*args, **kwargs)
  File "C:\Users\project\venvDB\envNames\py310_novae\lib\site-packages\sklearn\cluster\_agglomerative.py", line 532, in linkage_tree
    raise ValueError("Cosine affinity cannot be used when X contains zero vectors")
ValueError: Cosine affinity cannot be used when X contains zero vectors
```

**Comment by quentinblampey** [comment]
Hi @lidanwu, thanks for reporting!
Here, the issue happened when creating the hierarchies of prototypes. Can you look at the prototypes themselves, i.e. `model.swav_head.prototypes.data`, to see if there is any prototype with only zeroes?

I would be surprised if one prototype only has zeroes because we normalize them after each step, so it's an interesting issue.

Last question: did you use the public data from the tutorial or your own data?

> NB: I'll answer in January

**Comment by lidanwu** [comment]
Hi @quentinblampey, thanks for the tips. You are right that all `prototypes.data` has zero values. 
I managed to make the model training works after some diving into the code and data structure. Below is the details that may help to fix the code (or manual) for future usage. 

I used the public data from the tutorial and noticed that it came with a `counts` layer which contains only `nan` value. 
Running the normalization per instructions from tutorial (as shown below) did not change the values in `counts` layer (which makes sense since it overwrites the `adata.X`. 
```
novae.settings.auto_preprocessing = False # prevent Novae from running normalize_total / log1p
novae.utils.quantile_scaling(adatas)
```
I checked the code used inside[ `model.fit()`](https://github.com/MICS-Lab/novae/blob/main/novae/model.py#L566). There is a step to[ standardize](https://github.com/MICS-Lab/novae/blob/main/novae/utils/_validate.py#L95) the adata list. And that function would use `adata.layers['counts']` directly if `auto_preprocessing` is `False`. Since the tutorial said one should disable auto preprocessing, so the current code actually passes the `nan` value for training. 

To fix this, I manually copied the `adata.X`to `adata.layers['counts']` after the `quantile_scaling()` step before the model declaration.
![image](https://github.com/user-attachments/assets/24b19920-2728-49e7-b0d5-827e54c11003)

But the `prototypes.data` is **still all zeros** after training `model.fit(max_epochs=4, accelerator = "gpu",num_workers = 5)`.  
![image](https://github.com/user-attachments/assets/062d9376-97d5-4b0b-8ac5-20b88be62ea5)

Further investigation reveals that the input `adata.obsm['X_pca']` and `adata.obsm['X_umap']`  has all `nan` values too! The model initialization did trigger a message saying 

> [INFO] (novae.module.embed) Running PCA embedding initialization

The code seems to indicate that it's using `adata.X` directly instead of the saved pca embedding, so the `nan` issue with `layers["counts"]` and `obsm["X_pca"]` should **NOT** matter for model embedding initialization. 

But I **do** see non-zero model embedding after the initialization in `model.cell_embedder.embedding.weight` **AND** finally non-zero value in `model.swav_head.prototypes.data` after training this time! The subsequent `model.assign_domains()` also works  now. So it seems the `nan` values in `adata.obsm['X_pca']` affect the model training in ways independent of the embedding initialization.

**Comment by quentinblampey** [comment]
Hi @lidanwu, thanks for diving deep into this issue, it will save quite some time! I still try to fix that before mid-January

> The "protein mode" is still early, it should become more stable in the future.

**Comment by quentinblampey** [comment]
Hi @lidanwu, I took more time to look at this issue!

> I manually copied the adata.X to adata.layers['counts'] after the quantile_scaling() step before the model declaration.

Thanks for noticing that `adata.layers['counts']` was full of NA, I was not aware of that. However, it shouldn't matter because `novae` only uses `adata.X` for training. Indeed, the counts layer is used only to have a copy of the original counts (for the user purpose, not for novae).

> The code seems to indicate that it's using adata.X directly instead of the saved pca embedding, so the nan issue with layers["counts"] and obsm["X_pca"] should NOT matter for model embedding initialization.

You are right, the PCA initialization is using `adata.X` and not `adata.obsm["X_pca"]`.
I was not able to reproduce the issue, and I don't understand how `adata.obsm["X_pca"]` could be the origin of this...

Can you confirm that your issue is deterministic, i.e. that it always fails when having `adata.obsm["X_pca"]`, and that it always succeeds when removing it?

NB: I'll add a note in my todo-list to fix the nan counts / X_pca from the dataset, thanks again for noticing. Meanwhile, you can safely delete them.

**Comment by lidanwu** [comment]
Yes, the issue and solution were deterministic. I was using python 2.10 and followed the protein tutorials which says to disable auto-processing right after data download. I made it works by doing both: (1) copying adata.X to adata.layers["counts"] after quantile scaling; (2) delete adata.obsm["X_pca"].
